variables:
  - group: GITHUB_TOKEN_GP 

trigger:
  branches:
    include:
      - main  

pool:
  name: casa

steps:
  - checkout: self 

  # Eliminar el directorio cypress-tests existente (si ya existe, lo eliminamos)
  - script: |
      if [ -d "../cypress-dir/cypress-tests" ]; then
        rm -rf ../cypress-dir/cypress-tests
      fi
    displayName: 'Eliminar directorio cypress-tests existente'

  # Crear un directorio temporal fuera del repo del frontend para Cypress si no existe
  - script: |
      if [ ! -d "../cypress-dir" ]; then
        mkdir ../cypress-dir   # Crear un directorio fuera del repo del frontend
      fi
      cd ../cypress-dir      # Cambiar al nuevo directorio
      git clone https://github.com/FacuDePaul/Smartmove-cypress.git cypress-tests  # Clonar el repo de Cypress
    displayName: 'Clonar repo de Cypress en un directorio separado'

  # Instalar dependencias del frontend
  - task: NodeTool@0
    inputs:
      versionSpec: '18.20.4'  
    displayName: 'Instalar Node.js'

  - script: |
      npm install
    displayName: 'Instalar dependencias del frontend'

  # Instalar Cypress y ejecutar pruebas desde el nuevo directorio de Cypress
  - script: |
      cd ../cypress-dir/cypress-tests  # Cambiar al directorio donde clonamos las pruebas
      npm install       # Instalar dependencias de Cypress
      npx cypress run   # Ejecutar las pruebas de Cypress
    displayName: 'Correr pruebas de Cypress'

  # Si las pruebas pasan, realizar commit y push
  - script: |
      echo "Cambiando a la rama main"
      git checkout -B main  # Crear o moverse a la rama main
      git pull origin main  # Sincronizar con los últimos cambios
      git config user.email "lucaslopezvazquez1@gmail.com"
      git config user.name "kinjatoro"
      git add -A  # Asegurarse de agregar todos los cambios, pero no incluir carpetas innecesarias
      git commit -m "Commit automático después de pasar Cypress" || echo "No hay cambios para hacer commit"
      git push https://$(GITHUB_TOKEN)@github.com/kinjatoro/power-bi.git main
    displayName: 'Confirmar y pushear cambios'
    condition: succeeded()  # Solo si las pruebas pasaron