version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'  # Incluye todos los archivos generados
  base-directory: build  # Asegúrate de que esta ruta coincida con la salida de tu aplicación
cache:
  paths:
    - node_modules/**/*
