version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build

artifacts:
  base-directory: build  # Asegúrate de que esta ruta coincida con la salida de tu aplicación
  files:
    - '**/*'  # Incluye todos los archivos generados

cache:
  paths:
    - node_modules/**/*

frontend:
  phases:
    build:
      commands:
        - npm run build  # Este comando debe coincidir con el comando de construcción de tu app
  artifacts:
    baseDirectory: build  # Debe ser la carpeta donde se generan los archivos estáticos
    files:
      - '**/*'  # Archivos a desplegar
